import DOMPurify from 'dompurify'
import { setupApiWrapper } from './api-client.js'
import './protocol-ui.css'
import './style.css'
import './review.css'
import './state.js'
import './ui.js'
import './utils.js'
import './notify.js'
import './attachments.js'
import './timer.js'
import './inactivity.js'
import './speech.js'
import './api.js'
import './help.js'
import './landing.js'
import './contract.js'
import './roadmap.js'
import './steps.js'
import './done.js'
import './review.js'
import './settings.js'
import './history.js'
import { initApp } from './init.js'
import { bindEvents } from './event-bindings.js'

window.DOMPurify = DOMPurify
setupApiWrapper()
initApp()
window.addEventListener('DOMContentLoaded', bindEvents)
